FROM python:3.7

WORKDIR /opt/gitsu_etl

ENV PYTHONPATH "${PYTHONPATH}:/opt/gitsu_etl"

# Python Requirements
COPY requirements.txt .

# Add library to PYTHONPATH
RUN pip install -U pip

# # IF service_environment = 'dev'
RUN pip install -r requirements.txt

COPY requirements_freeze.txt .
RUN pip freeze
RUN pip freeze > /tmp/updated_requirements_freeze.txt
RUN diff --strip-trailing-cr \
	/tmp/updated_requirements_freeze.txt requirements_freeze.txt

# IF service_environment = 'dev' or 'stage'
# RUN pip install -r requirements_freeze.txt

# Notebooks Entry Directory
COPY . .
