FROM python:3.7

WORKDIR /opt/gitsu_etl

ENV PYTHONPATH "${PYTHONPATH}:/opt/gitsu_etl"

RUN pip install -U pip

# IF service_environment = 'dev'
COPY requirements.txt .
RUN pip install -r requirements.txt

# IF service_environment = 'prod' or 'stage'
COPY requirements_freeze.txt .
# RUN pip install -r requirements_freeze.txt

RUN pip freeze
RUN pip freeze > /tmp/updated_requirements_freeze.txt
RUN diff --strip-trailing-cr \
	/tmp/updated_requirements_freeze.txt requirements_freeze.txt

COPY . .
