# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
FROM jupyter/scipy-notebook:latest

ENV PYTHONPATH "${PYTHONPATH}:/opt/analytics"

WORKDIR /opt/analytics

# Juptyer Extensions
RUN jupyter labextension install @jupyterlab/toc
# RUN jupyter labextension install jupyterlab-drawio

# Python Requirements
COPY requirements.txt .

# Add library to PYTHONPATH
RUN pip install -U pip

# # IF service_environment = 'dev'
RUN pip install -r requirements.txt

COPY requirements_freeze.txt .
RUN pip freeze
RUN pip freeze > /tmp/updated_requirements_freeze.txt
RUN diff --strip-trailing-cr \
	/tmp/updated_requirements_freeze.txt requirements_freeze.txt

# IF service_environment = 'dev' or 'stage'
# RUN pip install -r requirements_freeze.txt

# Notebooks Entry Directory
COPY . .
WORKDIR /opt/gitsu_analytics/notebooks
EXPOSE 8888
