# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
FROM jupyter/scipy-notebook:latest

WORKDIR /opt/analytics

ENV PYTHONPATH "${PYTHONPATH}:/opt/analytics"

# Python Requirements
RUN pip install -U pip setuptools wheel

# Install dev
COPY requirements.txt .
RUN pip install -r requirements.txt

# Install prod
COPY requirements_freeze.txt .
# RUN pip install -r requirements_freeze.txt

# Check pip requirements for updates
RUN pip freeze 
RUN pip freeze > /tmp/updated_requirements_freeze.txt
RUN diff --strip-trailing-cr /tmp/updated_requirements_freeze.txt requirements_freeze.txt 

# Juptyer Extensions
RUN jupyter labextension install --debug @jupyterlab/toc

# Notebooks Entry Directory
COPY . .
WORKDIR /opt/gitsu_analytics/notebooks
EXPOSE 8888
